#!/usr/bin/env python2
import sys
import time
global text
if len(sys.argv) > 1:
  text = sys.argv[1:]
else:
  text = sys.stdin
def stringify(list):
  result = ""
  for i in list:
    result = result + " " + i
  return result[1:]
for i in stringify(text):
  time.sleep(0.07)
  sys.stdout.write(i)
  sys.stdout.flush()
  if i == "\n" or i == ".":
    time.sleep(0.7)
print("")
